# Generated by Django 2.0.7 on 2020-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200712_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_img',
            field=models.ImageField(null=True, upload_to='blog/static/blog/assets/images/post_pics'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
