# Generated by Django 2.0.7 on 2020-07-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200712_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tagcloud',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
